import "./globals.css";
import type { Metadata } from "next";

// Import Plus Jakarta Sans with all weights and styles
import "@fontsource/plus-jakarta-sans/200.css";
import "@fontsource/plus-jakarta-sans/200-italic.css";
import "@fontsource/plus-jakarta-sans/300.css";
import "@fontsource/plus-jakarta-sans/300-italic.css";
import "@fontsource/plus-jakarta-sans/400.css";
import "@fontsource/plus-jakarta-sans/400-italic.css";
import "@fontsource/plus-jakarta-sans/500.css";
import "@fontsource/plus-jakarta-sans/500-italic.css";
import "@fontsource/plus-jakarta-sans/600.css";
import "@fontsource/plus-jakarta-sans/600-italic.css";
import "@fontsource/plus-jakarta-sans/700.css";
import "@fontsource/plus-jakarta-sans/700-italic.css";
import "@fontsource/plus-jakarta-sans/800.css";
import "@fontsource/plus-jakarta-sans/800-italic.css";
import ProviderHeroUi from "@/context/provider-hero-ui";
import LoaderProvider from "@/context/provider-loader";
import ProviderAppShell from "@/context/provider-app-shell";

export const metadata: Metadata = {
  title: "Prodesarrollo",
  description: "Generated by nexa code",
  icons: [
    {
      rel: "icon",
      type: "image/svg+xml",
      url: "/pro-desarrollo-logo.svg",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ProviderHeroUi>
          <LoaderProvider>
            <ProviderAppShell>{children}</ProviderAppShell>
          </LoaderProvider>
        </ProviderHeroUi>
      </body>
    </html>
  );
}
